/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.2.1.217.3
    Soft IP Version: 1.6.0
    2022 12 01 00:11:13
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module PLL_sync_clk (clki_i, clkop_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clki_i;
    output  clkop_o;
endmodule